
package cn.oriki.cxf.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MobileAddressServiceService", targetNamespace = "http://service.cxf.oriki.cn/", wsdlLocation = "http://localhost:8080/oriki-cxf-spring-server/services/mobile?wsdl")
public class MobileAddressServiceService
    extends Service
{

    private final static URL MOBILEADDRESSSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MOBILEADDRESSSERVICESERVICE_EXCEPTION;
    private final static QName MOBILEADDRESSSERVICESERVICE_QNAME = new QName("http://service.cxf.oriki.cn/", "MobileAddressServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/oriki-cxf-spring-server/services/mobile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOBILEADDRESSSERVICESERVICE_WSDL_LOCATION = url;
        MOBILEADDRESSSERVICESERVICE_EXCEPTION = e;
    }

    public MobileAddressServiceService() {
        super(__getWsdlLocation(), MOBILEADDRESSSERVICESERVICE_QNAME);
    }

    public MobileAddressServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOBILEADDRESSSERVICESERVICE_QNAME, features);
    }

    public MobileAddressServiceService(URL wsdlLocation) {
        super(wsdlLocation, MOBILEADDRESSSERVICESERVICE_QNAME);
    }

    public MobileAddressServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOBILEADDRESSSERVICESERVICE_QNAME, features);
    }

    public MobileAddressServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileAddressServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MobileAddressService
     */
    @WebEndpoint(name = "MobileAddressServicePort")
    public MobileAddressService getMobileAddressServicePort() {
        return super.getPort(new QName("http://service.cxf.oriki.cn/", "MobileAddressServicePort"), MobileAddressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileAddressService
     */
    @WebEndpoint(name = "MobileAddressServicePort")
    public MobileAddressService getMobileAddressServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cxf.oriki.cn/", "MobileAddressServicePort"), MobileAddressService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOBILEADDRESSSERVICESERVICE_EXCEPTION!= null) {
            throw MOBILEADDRESSSERVICESERVICE_EXCEPTION;
        }
        return MOBILEADDRESSSERVICESERVICE_WSDL_LOCATION;
    }

}
